### ISSUE TITLE
Problems with scala mode

### ISSUE THREAD

**Issue by rockjam** [scaled/scaled#7]
After I built scaled from scratch, I get this exception when opening scala files. And features of scala mode are not working. Could it be a classpath issue? Can you give some help on debugging it? I tried to add some logging in scaled.project.ScalaExtractorPlugin, but could not get a full classpath there.    

```
scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	at scala.reflect.internal.Mirrors$RootsBase.scala$reflect$internal$Mirrors$RootsBase$$$anonfun$4(Mirrors.scala:54)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:54)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:173)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage$lzycompute(Definitions.scala:161)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage(Definitions.scala:161)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass$lzycompute(Definitions.scala:162)
	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass(Definitions.scala:162)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1400)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
	at codex.extract.ScalaExtractor.process0(ScalaExtractor.scala:74)
	at codex.extract.ScalaExtractor.process(ScalaExtractor.scala:27)
	at scaled.project.Indexer.scaled$project$Indexer$$$anonfun$7(Indexer.scala:68)
	at scaled.project.Indexer.scaled$project$Indexer$$$anonfun$7$adapted(Indexer.scala:66)
	at scaled.Option.foreach(Option.scala:27)
	at scaled.project.Indexer.reindex(Indexer.scala:66)
	at scaled.project.Indexer.scaled$project$Indexer$$$anonfun$3(Indexer.scala:38)
	at scaled.project.Indexer.scaled$project$Indexer$$$anonfun$3$adapted(Indexer.scala:38)
	at scaled.impl.Plumbing$$anon$2.run(Plumbing.scala:25)
	at scaled.impl.Plumbing.run(Plumbing.scala:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by samskivert** [comment]
What features of Scala mode aren't working?

That particular error is from the indexer which is trying to extract metadata from the Scala files by running them through the compiler. But if the Scala code is not from a project that Scaled can recognize, it doesn't know what version of scala-library.jar to put on the classpath, so when it tries to use the compiler to run the indexer, it will fail.

I should probably just prevent the indexer from running in that case.

**Comment by rockjam** [comment]
Code highlighting works fine, show type or show value does not work. I'm trying to browse sbt project, and have sbt-project installed. But I havent found command to import project.

**Comment by samskivert** [comment]
Unfortunately, Scaled does not currently have good support for SBT projects. But even if you did use a project type which it supports well (Maven or Scaled's internal project type), it doesn't have great support for obtaining metadata from the Scala compiler. I'd like to just integrate Ensime at some point because it's looking increasingly less likely that I'm ever going to finish the custom integration with SBT or the Scala compiler as that's a constantly moving target and a complex one to boot.

**Comment by bbarker** [comment]
how about https://github.com/Microsoft/language-server-protocol, seems to be the way of the future, assuming dotty is the future...

**Comment by bbarker** [comment]
Also LSP would hopefully make supporting other languages easier
